import utils from '../utils.js';
let { randomString } = utils;

let example = [
	{
		"id":"3416398222",
		"text":"Watson has returned from Afghanistan.",
		"type":"claim",
		"label":"premise",
		"open":true,
		"display":true,
		"indent":0,
	},
	{
		"id":"0612363605",
		"text":"Watson is an English army doctor who has undergone hardship and sickness, and has injured his arm.",
		"type":"premise",
		"label":"premise",
		"open":true,
		"display":true,
		"indent":1,
	},
	{
		"id":"0604910087",
		"text":"Watson is an English army doctor.",
		"type":"premise",
		"label":"premise",
		"open":true,
		"display":true,
		"indent":2,
	},
	{
		"id":"7663040203",
		"text":"He is a gentleman of a medical type.",
		"type":"premise",
		"label":"premise",
		"open":true,
		"display":true,
		"indent":3,
	},
	{
		"id":"8573607752",
		"text":"He has the air of a military man.",
		"type":"premise",
		"label":"premise",
		"open":true,
		"display":true,
		"indent":3,
	},
	{
		"id":"1562350060",
		"text":"[Watson is English.]",
		"type":"premise",
		"label":"premise",
		"open":true,
		"display":true,
		"indent":3,
	},
	{
		"id":"6529481994",
		"text":" He has undergone hardship and sickness.",
		"type":"premise",
		"label":"premise",
		"open":true,
		"display":true,
		"indent":2,
	},
	{
		"id":"4849050644",
		"text":"He has a haggard face.",
		"type":"premise",
		"label":"premise",
		"open":true,
		"display":true,
		"indent":3,
	},
	{
		"id":"4140692662",
		"text":"His left arm has been injured.",
		"type":"premise",
		"label":"premise",
		"open":true,
		"display":true,
		"indent":2,
	},
	{
		"id":"5709295021",
		"text":"He holds it in a stiff and unnatural manner.",
		"type":"premise",
		"label":"premise",
		"open":true,
		"display":true,
		"indent":3,
	},
	{
		"id":"5247891985",
		"text":"He has just come from the tropics.",
		"type":"premise",
		"label":"premise",
		"open":true,
		"display":true,
		"indent":1,
	},
	{
		"id":"7538799266",
		"text":"His face is dark.",
		"type":"premise",
		"label":"premise",
		"open":true,
		"display":true,
		"indent":2,
	},
	{
		"id":"6424974159",
		"text":"This is not the natural tint of his skin.",
		"type":"premise",
		"label":"premise",
		"open":true,
		"display":true,
		"indent":2,
	},
	{
		"id":"8948168165",
		"text":"His wrists are fair.",
		"type":"premise",
		"label":"premise",
		"open":true,
		"display":true,
		"indent":3,
	},
	{
		"id":"8328047230",
		"text":"The only place in the tropics where an English army doctor could have seen much hardship and got his arm wounded is in Afghanistan.",
		"type":"premise",
		"label":"premise",
		"open":true,
		"display":true,
		"indent":1,
	}
];

export default example;